---
  defaults: &defaults
    host: localhost
    adapter: postgresql
    encoding: utf8
    database: alcohol_finder_<%= Rails.env.downcase.try(:strip) %>
    username: postgres
    password:
    reconnect: false
    min_messages: warning

  development:
    <<: *defaults
  
  test:
    <<: *defaults
  
  production:
    <<: *defaults
